function print_table(dat,ids)

Sub_dat = dat(ismember(dat.iso_id, ids),:);
[~,I] = sort(Sub_dat.C_T,'descend');
Sub_dat = Sub_dat(I,:);
for i = 1:size(Sub_dat,1)
    fprintf('%s & $%d$ & $%d$ & $%d$ & $%0.2e$ & $%0.2e$ & $%0.2e$ & $%0.2e$ & $%0.2e$ & $%0.2e$ & $%0.2e$ & $%0.2e$ & $%0.2e$\\\\\n',...
    Sub_dat.iso_id(i),...
    Sub_dat.C_T(i),...
    Sub_dat.R_T(i),...
    Sub_dat.D_T(i),...
    Sub_dat.alpha_0(i),...
    Sub_dat.alpha(i),...
    Sub_dat.beta(i),...
    Sub_dat.gamma(i),...
    Sub_dat.delta(i),...
    Sub_dat.eta(i),...
    Sub_dat.kappa(i),...
    Sub_dat.n(i),...
    Sub_dat.log_wA(i));
end
